# -----------------------------------------------------------------------------
# Stage 1 option C: Build with your Dockerfile (full control) + push
# Stage 2: Generate ISO
# -----------------------------------------------------------------------------
---
kind: Secret
apiVersion: v1
metadata:
  name: my-dockerfile
  namespace: default
type: Opaque
stringData:
  Dockerfile: |
    FROM quay.io/kairos/kairos-init:v0.7.0 AS kairos-init
    FROM opensuse/leap:15.6
    ARG MODEL=generic
    ARG VERSION=v3.6.0
    COPY --from=kairos-init /kairos-init /kairos-init
    RUN /kairos-init -l debug -s install -m "${MODEL}" --version "${VERSION}" && \
        /kairos-init -l debug -s init -m "${MODEL}" --version "${VERSION}" && \
        rm -f /kairos-init
---
apiVersion: build.kairos.io/v1alpha2
kind: OSArtifact
metadata:
  name: full-control-dockerfile
  namespace: default
spec:
  image:
    dockerfile:
      ref:
        name: my-dockerfile
        key: Dockerfile
      # templateValuesFrom: { name: my-template-values }
      # templateValues: { SomeVar: "value" }
    push:
      imageName: my-registry.example.com/my-ns/full-control-kairos:latest
      credentialsSecretRef:
        name: registry-credentials

  artifacts:
    arch: amd64
    iso: true
    cloudConfigRef:
      name: cloud-config
      key: userdata

  exporters: []
