resources:
- manager.yaml

patches:
- path: manager_env_patch.yaml
  target:
    kind: Deployment
    name: kairos-operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/kairos/operator
  newTag: v0.2.2@sha256:854198e1e418315c49b55595e0268ca98ea0729403d75cdf17e3f55aabddb3b9
