apiVersion: apps/v1
kind: Deployment
metadata:
  name: kairos-operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace