apiVersion: operator.kairos.io/v1alpha1
kind: NodeOp
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: nodeop-sample
spec:
  # The container image to run on each node
  image: busybox:latest
  # The command to execute in the container
  command: ["sh", "-c", "echo 'Hello from node' && hostname"]
  # Cordon the node before running the operation
  cordon: true
  # Drain options for pod eviction
  drainOptions:
    # Enable draining
    enabled: true
    # Force eviction of pods without a controller
    force: false
    # Grace period for pod termination (in seconds)
    gracePeriodSeconds: 30
    # Ignore DaemonSet pods
    ignoreDaemonSets: true
    # Delete data in emptyDir volumes
    deleteEmptyDirData: false
    # Timeout for drain operation (in seconds)
    timeoutSeconds: 300
