apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default

# Override the image patch from default to use controller:latest
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: controller:latest
  target:
    kind: Deployment
    name: kairos-operator
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kairos-operator
    spec:
      template:
        spec:
          containers:
          - name: manager
            env:
            - name: NODE_LABELER_IMAGE
              value: controller-node-labeler:latest
  target:
    kind: Deployment
    name: kairos-operator

images:
- name: controller
  newName: controller
  newTag: latest
