name: Release Orchestrator

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: [lint, test]
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ github.ref_name }} 